### PR TITLE
fix(subcommands): add subcommand specific cooldown

### LINKED ISSUE #498: bug: default cooldowns are ran twice for subcommands
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

If you set a global default cooldown and attempt to run a command using the subcommand plugin, the rate limit bucket will be consumed twice. If the limit is 1, the command can never be ran.

Reference: https://discord.com/channels/737141877803057244/737142940777971773/1171224384770416730

### Steps To Reproduce

1. Create a SapphireClient with the following default cooldown options:
```ts
defaultCooldown: {
    limit: 1,
    delay: 5000 // 5 Seconds
},
```
2. Create a command that uses the subcommand plugin and has a subcommand.
3. Attempt to run the command.

### Expected behavior

The command should be able to be ran once before hitting the rate limit.

### Screenshots

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by favna**
fixes #498

### CODE REVIEW

File: packages/subcommands/src/lib/Subcommand.ts [hunk 1]
```diff
@@ -570,7 +574,7 @@ export namespace Subcommand {
 	export type Options = SubcommandOptions;
 	export type JSON = Command.JSON;
 	/** @deprecated Use {@linkcode LoaderContext} instead. */
-	export type Context = LoaderContext;
+	export type Context = Command.LoaderContext;
```
Comment (kyranet) [inline packages/subcommands/src/lib/Subcommand.ts:577]: This is intended, it aliases the line below.

File: packages/subcommands/src/lib/precondition-resolvers/index.ts [hunk 2]
```diff
@@ -0,0 +1 @@
+export * from './subcommandCooldown';
```
Comment (kyranet) [inline packages/subcommands/src/lib/precondition-resolvers/index.ts:1]: What's the purpose for a single-file export?

File: packages/subcommands/src/lib/types/Events.ts [hunk 3]
```diff
@@ -91,7 +91,7 @@ declare module 'discord.js' {
 		[SubcommandPluginEvents.ChatInputSubcommandNotFound]: [
 			interaction: ChatInputCommand.Interaction,
 			subcommand: ChatInputCommandSubcommandMappingMethod,
-			context: ChatInputCommand.RunContext
+			context: ChatInputCommand.Context
```
Comment (kyranet) [inline packages/subcommands/src/lib/types/Events.ts]: Revert this

File: packages/subcommands/src/preconditions/PluginSubcommandCooldown.ts [hunk 4]
```diff
@@ -0,0 +1,130 @@
...
+		const rateLimit = this.getManager(subcommand, context).acquire(cooldownId);
+
+		if (rateLimit.limited) {
+			const remaining = rateLimit.remainingTime;
+
+			return this.error({
+				identifier: SubcommandIdentifiers.SubcommandPreconditionCooldown,
+				message: `There is a cooldown in effect for this ${commandType} subcommand. It'll be available at ${new Date(
+					rateLimit.expires
+				).toISOString()}.`,
```
Comment (kyranet) [inline packages/subcommands/src/preconditions/PluginSubcommandCooldown.ts:81]: This should use `time()` instead, as you recommended me.

That means... PR to /framework, sigh, you two called it.

**Review by kyranet — CHANGES_REQUESTED** [review]

**Review by kyranet — APPROVED** [review]
